default:
  saNamespace: argo-workflows

serviceAccounts:
  - name: user-default-login
    tokenName: user-default-login
    isClusterRB: true
    role: view
    rbacRule: true
    rbacPrecedence: 0
    
# the name of the roles should be updated to correspond with the argo workflows deployment
  - name: app1-admin-sa
    tokenName: argo-workflows-admin-sa-token
    isClusterRB: false
    isClusterRole: false
    role: app1-admin
    rbacRule: "'app1-team' in groups"
    rbacPrecedence: 10
    managedNamespace: app1
    namespace: app1