---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  source:
    path: ./20-argo-workflows/argo-wf-config
    repoURL: https://github.com/alvarolop/spring-batch-capitalator.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
...
