---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  source:
    path: argo-workflows/argo-wf-config
    repoURL: https://github.com/alvarolop/spring-batch-capitalator.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-argowf.yaml
        - values-dex.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
...
