global:
  name: argowf
  namespace: argo-workflows
  ocp:
    baseUrl: apps.ocp.sandbox2972.opentlc.com
  createNamespaces:
    - app01-workflows
    - app02-workflows
  
grafana:
  name: grafana
  namespace: grafana
  app: argo-workflows
  dashboards:

    - name: argo-metrics
      folder: "Argo Workflows"
      path: "dashboards/ARGO-Metrics.json"
      
    - name: argoworkflow-metrics
      folder: "Argo Workflows"
      path: "dashboards/ArgoWorkflow-metrics.json"

rbac:
  # Users will be assigned ONLY one SA based on the first rule that matches the groups of the user.
  # Please, make sure to follow the correct order of precedence.
  # Possible roles are admin, edit, view.
  
  - group: cluster-admins
    role: admin
    clusterWide: true
    precedence: 100

  - group: app01-wf-admins
    role: admin
    namespaces:
      - app01-workflows
    precedence: 90

  - group: app01-wf-viewers
    role: view
    namespaces:
      - app01-workflows
    precedence: 80
